---

plugins:
  # https://github.com/babel/eslint-plugin-babel
  - babel
  - import

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true

# https://github.com/babel/babel-eslint
parser: babel-eslint

extends:
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'airbnb-base'

rules:
  no-console: 0
