---

plugins:
  - babel
  - jest


env:
  node: true
  jest: true


parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'

rules:
  no-console: 0
  import/extensions: 0
