name: build
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: make install
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID=<ccfa888f2e1007081b043c04e70bb4330f1e52016d3daa79f001d7f3eb06cbab>
        with:
          coverageCommand: make test-coverage
          debug: true
